### ISSUE TITLE
Bug al declarar un recurso con el mismo nombre de clase que otro

### ISSUE THREAD

**Issue by k7k0** [SIU-Toba/rest#3]
Suponiendo que uno tiene estos archivos en toba_referencia:
```
#Deportes
/rest/deportes/recurso_deportes.php

#Deportes de una persona
/rest/personas/recursos_deportes.php
```

En la version de la librería que tiene toba 2.6 esto funciona, pero en la versión nueva:

```
Fatal error: Cannot redeclare class recurso_deportes in /var/local/toba/proyectos/toba_referencia/php/rest/deportes/recurso_deportes.php on line 11
```

No suena muy bien definir dos clases con el mismo nombre. Tampoco tiene sentido que uno no pueda definir un subrecurso igual que otro subrecurso. Este caso de uso es muy común con las entidades de nuestros sistemas, y seria raro modificar el nombre del recurso por este motivo (por ejemplo esto: `personas/18/deportes-de-persona`)

Una que se me ocurre es poder separar lo que es el nombre de la clase del nombre del recurso. Por ejemplo:
``
#Deportes de una persona
/rest/personas/recurso_personas_deportes.php
``
Y que dentro uno tenga
```
/**
 * @rest-recurso deportes
 **/
class recurso_personas_deportes
{
...
}

```

¿Ideas?

**Comment by aacotroneo** [comment]
Pedir que si quieren nombres repetidos usen namespaces? :P (me llega al
mail esto.. no pude evitar contestar)

**Comment by k7k0** [comment]
> Pedir que si quieren nombres repetidos usen namespaces? 

Capaz anda. 
Esta bueno que en el editor te salte con un nombre distinto el archivo también. Si pudiera elegir me gustaria que quedara el caminito completo en el nombre de clase/archivo. Ej
```
recurso_personas.php
recurso_deportes.php
recurso_personas_deportes.php
```

¿Se podrá atrapar alguna annotation a nivel clase para pisar el nombre del recurso, que tan adentro esta metido "nombre clase = nombre sub-recurso" en el codigo?

> (me llega al mail esto.. no pude evitar contestar)
Mandalo a spam!! :P

**Comment by aacotroneo** [comment]
Puedo deshabilitarlo facil el spam!! lo tengo de chusma :P
