### ISSUE TITLE
Recursos que tengan _ en el filneme

### ISSUE THREAD

**Issue by serjae** [SIU-Toba/rest#5]
No puedo usar _ en los nombres de los recursos. Las clases de REST hacen como una conversión de _ a / y eso hace que no funcionen los recursos que tengan _. 

Cómo puedo hacer para utilizar recursos que tenga _ en el filename?

**Comment by k7k0** [comment]
Buenas! Pasanos un "svn info" de la carpeta toba, para ver en donde estan parados.
Tuvimos un par de regresiones con este tema, pero creo que en la ultima de 2.7 deberia andar bien (mañana probamos)
